### PR TITLE
Restructure repository_manager and update service_endpoint_manager

### PR DESCRIPTION
**Pull request by Hazhzeng**
### Structure Changes
1. Pull out git utilities into a separate file **./respository/local_git_utils.py**
2. Pull out and generalized exceptions into **./exceptions.py**
3. Remove **RepositoryResponse** from **./respository/repository_manager.py** because the repository creation flow is now controlled by exception handling instead of returning status code. In this way, we allow the user to handle error emission more flexibly
4. Distinguish functions that perform local git repository control in **./respository/repository_manager.py**, all functions contain "local_git" in the name are intended to deal with the local git repository, otherwise, they control the Azure Devops Repository

### Utils
1. Create two functions **construct_git_remote_name** and **construct_git_remote_url** in **./respositoy/repository_manager.py** for generating valid **git remote name** and **git remote url**. All special characters except '-' and '_' will be translated into '-' by the **_sanitize_git_remote_name** function.
2. Create a function **_get_service_endpoint_name** in **./service_endpoint/service_endpoint_manager.py** for unifying the service endpoint name.

### Miscellaneous
1. Fix **./yaml/templates/build.jinja** template to generate the correct vmImage value. (It needs to be wrapped with quotes/double quotes)

### Todo
1. The **./respository** folder is misspelled and it should be changed to **./repository**, as well as the file reference in [Azure CLI](https://github.com/Azure/azure-cli). The typo fix will be in a separate PR.

### CODE REVIEW

**Comment by Francisco-Gamino** [comment]
cc: @asavaritayal, @ahmelsayed @maiqba11

**Comment by maiqbal11** [comment]
Hi @Hazhzeng, from a refactoring perspective, this looks fine to me. I will say that it's hard for me to to provide specific comments because I have very little context on the actual implementation from before. Even after reading through the large flow charts and design docs in the shared notes, it's still challenging to judge how this PR fits into the larger whole. 

Just some notes for the future:

1. It would be better if you could break up your change into smaller PRs, especially considering that few of us have context on the contents of this repo. Smaller changes that are self-contained (and easier to revert if needed) are simpler to understand. 
2. Looks like there are already tests present in this repo and but there's no CI set up to take advantage of them. With a refactoring change like this, the key would be to make sure that it doesn't break existing functionality. You might be able to run them locally but it would be awesome to have them displayed here. Let me know if you need help setting this up.

**Comment by Hazhzeng** [comment]
Much appreciated @maiqbal11, let me try to link up the unit tests and make it a github check.
If I overcome any issues, will let you know. Cheers!

**Comment by Francisco-Gamino** [comment]
Thank @maiqbal11 for review this!

**Pull request merged**
